### ISSUE TITLE
Treat N/A like 100% instead of 0%.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/crf-heat-map#104]
# Test Notes 
- Drag a top slider below 100% and verify that it filters out N/A cells.

# Development Notes
i know we've gone back and forth over this but perhaps we add radio buttons that treat N/A like either 0% or 100%

**Comment by pburnsdata** [comment]
So it was treating them as 100% already but I didn't account for it in the filtering (which is what Heather noticed and may have thought was it acting as 0%), so just added that. I haven't heard anyone wanting it treated as 0% late;y so gonna hold off on the radio buttons.
