### ISSUE TITLE
Consider removing filters with one unique value.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/crf-heat-map#114]
i doubt every study needs the the analysis subsetters (_Subset 1_, _Subset 2_, _Subset 3_).  they might be worth optionalizing, either when the variables don't exist or are constant.

# Test Notes
* Set all values of a filter variable equal to the same value and render that chart.  That filter should not show up, and a note should print to the console that it was removed.
  1. Download the data file.
  2. Delete all values in any of these columns: status, subjfreezeflg, sitename, subset1, subset2, subset3.
  3. Upload the edited data file and re-render the chart.
  4. The filter representing the edited column should not appear.

**Comment by danedexF5** [comment]
@samussiah  deleted sitename and status. Both were removed and both printed to console but all other nesting filters were also removed. This is probably expected behavior but wanted to note it.
