### ISSUE TITLE
Add option for using a form ordinal in the dataset for ordering the forms 

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#116]
Currently, the forms are listed in alphabetical order if they are displayed in the heatmap.  Heather requested that we add an option for ordering the forms by form ordinal if it is provided in the dataset.

# Test Notes
- Forms are ordered by the `form_ordinal` variable by default. (Set the top level nesting variable to "Form" and verify that the form at the top is "DM")
- Remove the form_ordinal setting and verify that forms display alphabetically instead

**Comment by danedexF5** [comment]
works as expected
