### ISSUE TITLE
Turn off text wrapping for the y-axis labels and end it with ... and put full label in hover

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#117]
# Test Notes
- Download the CAT data (use the csv export on the Preview page, not the export on the main page), add a lengthy value in the sitename column like "wow, this is really lengthy-I'm  kind of shocked at how lengthy this has gotten", and upload the updated file.
- Verify that this ID value in the heatmap does not wrap, gets cut off, and that you can see the full text by hovering over it.

**Comment by danedexF5** [comment]
This was wrapping with FF, talked to @pburnsdata about it and he said to use the floor-percentages branch, I did and it worked there.
