### ISSUE TITLE
Update filter logic to work with Webcharts v1.11.4.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/crf-heat-map#119]
update _All_ filter logic in case _All_ appears in the data

https://github.com/RhoInc/Webcharts/issues/236

# Test Notes
1) Download the CAT data, add an "All" value in the "Status" column and upload the updated file.
2) Select the top "All" option from the Subject Status dropdown and verify that all chart data is displayed.
3) Select the second "All" option and verify that only a subset is displayed.

**Comment by samussiah** [comment]
Tested in Webcharts

**Comment by danedexF5** [comment]
@samussiah said this can be skipped
