### ISSUE TITLE
Percentage column filters should floor the percentages in the table before comparing them to the specified upper percentage.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/crf-heat-map#133]
i.e. if a percentage is anywhere between 99 and 99.9 and the column filter is set to 99 that percentage should be included.  and on the other side if a percentage is anywhere between 0.1 and 1 and the column filter is set to 1 that percentage should be included.

since we're dealing with integers and not decimals there's a disconnect between the displayed percentages and their actual values

# Test Notes
- Set the column filter boxes to two numbers that are the same as values in that column and verify that both rows do not disappear. (e.g. using the default data set the filter for Entered to 39% - 76% and verify that the rows with 76% and 39% both stay.

**Comment by danedexF5** [comment]
@samussiah One issue. Using the ranges in the test notes, a row with 77% still appears and it greys out for a background color. In FF it also appears bu the two 76% rows also grey out.

**Comment by danedexF5** [comment]
talked to @samussiah about this. he said "when a row grays out it means it doesn't meet the criteria but it does have a nested row that meets the criteria" so with that, this passes.
