### ISSUE TITLE
Add filters as tab in report.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/crf-heat-map#169]
# Test Notes
1. Change some filters on the renderer
2. Click the "Report" button and verify that a filters tab appears in the report that matches the currently selected filters.

**Comment by pburnsdata** [comment]
@samussiah I purposely didn't include them in the report export because they ignore filters and just print out the nests that are built in. That was my understanding of the request but I'll check with Heather and make sure that's true

**Comment by samussiah** [comment]
Makes sense, but the report does update with the filters, right?

**Comment by pburnsdata** [comment]
ahh yes - you are totally right and that was not intentional... haha

**Comment by pburnsdata** [comment]
I'll see if Heather wants that!
