### ISSUE TITLE
subjectnameoridentifier report, site & subject status & subject freeze status are blank *See screenshot*

### ISSUE THREAD

**Issue by rchronowic** [RhoInc/crf-heat-map#173]
# Test Notes
- Click on the report button and verify that in the report the subject-level columns listed in the title of this issue are not blank where their headers appear.
- These columns should only appear if there's a subject column (e.g. the first tab of the report shouldn't have them, but the other three should)

Possible bug?

![image](https://user-images.githubusercontent.com/42471621/67768757-901e0380-fa29-11e9-93f6-fd9b4c0c97ab.png)

**Comment by danedexF5** [comment]
So I'm getting exports that simply don't have those 3 columns, which i think is a pass but wanted to make sure since the test is written a little differently.
