### ISSUE TITLE
Rename Repo

### ISSUE THREAD

**Issue by jwildfire** [RhoInc/crf-heat-map#2]
I'm not crazy about the repo name. It doesn't really explain what the tool does, and it specifies a single COTS system (RAVE), when in fact this graphic should work fine with any DMS. (I'm also not crazy about the missing 'e', but fully admit that I'm just being picky there)

What about something like 'data-disposition-explorer' or 'data-cleaning-summary' or 'clinical-data-status'?

**Comment by brittsikora** [comment]
What shall it be called?

**Comment by samussiah** [comment]
_crf-heat-map_ shall be its namesake

**Comment by pburnsdata** [comment]
and so concludes the story of how the rave-xplorer became the crf-heat-map and Jeremy once again found peace.
