### ISSUE TITLE
Use new columns OPEN_QUERY_CNT and ANSWER_QUERY_CNT to calculate query related values

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#29]
Heather added two new columns to the rx_DataPage csv for us so that we can use those to calculate query related values instead of trying to pull in the data from the separate query csv file.  We need to adjust the calculations so that they reference the new data.

## Test Notes
 - No testing needed

**Comment by samussiah** [comment]
update query calculation from `[].length` to `d3.sum()`
