### ISSUE TITLE
Decide whether N/A cells are treated as 0 or 100 when applying the column sliders.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/crf-heat-map#37]
## Test Notes
- Verify that N/A cells are labeled as such 
- Verify that N/A cells are the same color as 100% columns (Dark blue)

**Comment by samussiah** [comment]
Currently treated as 100% in `performance-again` branch.

**Comment by pburnsdata** [comment]
That makes the most sense to me, sense both 100% and N/A require no action and are colored the same color
