### ISSUE TITLE
Rename options in "Show Status for:" drop-downs

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#41]
Update option names within the "Show Status for:" drop-downs to:

- sitename = Site Name

- subjectnameoridentifier = Subject ID

- foldername = Folder

- formoid = Form

## Test Notes
- Verify you can add custom labels to nesting columns
- Verify that the nest names appear in the chart as Emily specified above.

**Comment by samussiah** [comment]
related to #45 , i.e. specify nesting columns as objects with label properties
