### ISSUE TITLE
Make subset drop-down fields the same width

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#42]
Make subset drop-down fields a uniform width that will support 10 characters

## Test Notes
- The 3 subset drop downs should have equal widths
- The webcharts controls should be left of the table, and the nesting controls should be above the ID column
- The moving of the data export to the top is handled in #56 and hasn't been implemented so don't check for this.

**Comment by samussiah** [comment]
move webcharts controls to the left of the table, nesting controls above the ID column, data export above webcharts controls and to the left of the nesting controls.

@pburnsdata leave this one for last and if you don't have time I'll take this one.
