### ISSUE TITLE
Remove filter columns from the first tab of the export spreadsheet

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#44]
DMEDS likes the addition of the second tab within the export spreadsheet that now lists which filters a user had selected to produce the current export.  The filter columns can be removed from the first tab of the spreadsheet now.

## Test Notes
- Verify that a csv export contains information on the currently applied filters
- Verify that an xlsx export contains information on the currently applied filters in the second tab but does not in the first tab.

**Comment by samussiah** [comment]
Update .csv export to print current filters after the last data column.
