### ISSUE TITLE
Speed Improvements

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/crf-heat-map#5]
Pretty slow when changing filters right now, so might want to change the way data is processed.

## Test Notes
- No need for testing here as this was a relative improvement (no set loading time goals currently- might add unit test later?)

**Comment by pburnsdata** [comment]
Interested in whether or not you have any thoughts on how to make this quicker . Most of the preprocessing is happening [here].(https://github.com/RhoInc/rave-xplorer/blob/master/src/flattenData/processData.js)

**Comment by emmorris** [comment]
Load in the fake dataset Heather provided in the email from June 8 and see how bad the load times are.  We may need to continue to explore options for performance improvements.
