### ISSUE TITLE
Move data export to top left.

### ISSUE THREAD

**Issue by samussiah** [RhoInc/crf-heat-map#56]
currently Webcharts looks for the export nodes within the `table.wrap` so relocating the nodes outside of the Webcharts container breaks things.  We could either leave the exports at the bottom or recreate them in the top left.

**Comment by emmorris** [comment]
@samussiah, looks like you decided to leave the export buttons at the bottom for now unless I'm looking at an old version.  

Is that correct?

**Comment by samussiah** [comment]
Yeah, it's gonna take a little bit more work to move it to the top left because of how Webcharts attaches the data to the button.  Maybe v1.1.

**Comment by samussiah** [comment]
Duplicate of #43
