### ISSUE TITLE
Correct Order of Visits

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/crf-heat-map#6]
# Test Notes
- Set the nests up to include Folder and verify that the folders are sorted numerically instead of alphabetically (e.g. visit 1 should be followed by visit 2 not visit 11.)  

# Development Notes

Right now, when showing status for foldername, results are sorted alphabetically so visit 7 is after visit 69 etc.

**Comment by samussiah** [comment]
If all studies had a standard set of visit names like Visit 7 and Visit 69 this wouldn't be too hard but a lot of times studies have more descriptive visit names like Screening, Randomization, Day 1, 3 Month Visit, etc.  Not sure the best way to go about this until we've seen more data.
