### ISSUE TITLE
Poor performance coming from Webcharts Code

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/crf-heat-map#87]
So currently, a lot of the slow down on complicated nests is coming from the heat maps interaction with 
webcharts code.

Here's an example where a subject : folder : form nest took 2 minutes :
![performance viz](https://user-images.githubusercontent.com/26064686/44663412-0414e400-aa00-11e8-9200-16778a1f9fe7.JPG)

Here's the piece of code that's the main offender - commenting it out caused a big performance boost.
![webcharts speed code](https://user-images.githubusercontent.com/26064686/44663423-0bd48880-aa00-11e8-9691-e9896fc7190d.JPG)

The relevant code can be found here:
https://github.com/RhoInc/Webcharts/blob/master/src/table/draw.js

It seems to be grabbing the width of the first table header to determine if it needs to alter table layout if the table is narrower than table top or bottom.

**Comment by samussiah** [comment]
nice find @pburnsdata !  would you put in a webcharts issue to address this?

**Comment by dschwentker** [comment]
Tested and confirmed speed is increased compared to master. Browser no longer prompts to kill script that is running, though the third nested level when selecting Subject ID/Folder/Form still takes around 15 seconds or so to load.
