### ISSUE TITLE
Add Percentage to Greyed Out Cells 

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#91]
In the latest update we greyed out the cells when the slider was set to 50 or below.  DMEDS has requested that we continue to show the percentage text over the cell even if it is greyed out.  
# Test Notes
- Set a slider so that a gray parent row appears that did not meet the criteria, but has children that do.
- Verify that the values for the gray parent row still appear and appear in black text.

**Comment by dschwentker** [comment]
Tested and passed.
