### ISSUE TITLE
Add study averages as top row for each column

### ISSUE THREAD

**Issue by emmorris** [RhoInc/crf-heat-map#92]
Add study averages as top row for each column. Request from DMEDS, but low priority.

**Comment by jwildfire** [comment]
Good idea. Should be pretty trivial to add if we just make "Overall" the top level of the nest by default. Basically: 

```
chart.on("init",function(){
   this.raw_data.forEach(function(d){
       d.overall = "Overall"
    })
})
config.levels = d3.merge(["overall"],config.levels])
```

**Comment by dschwentker** [comment]
Tested and confirmed that the new "Overall" bar is added at the top of the chart showing study averages as a top row for each column.
