### ISSUE TITLE
Round percentages down

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/crf-heat-map#96]
Sometimes when cells are near 100% but not they appear as 100% which is misleading. Going to round all percentages down to the nearest integer.

# Test Notes
- Verify that site 106-RhoTest has 42% entered, not 43%, both in the heat map table and in the exports.
(Or find another cell that would differ, now that everything is rounded down)

**Comment by dschwentker** [comment]
Tested and confirmed that numbers are now being rounded down
