### ISSUE TITLE
Add info bubbles to column headers

### ISSUE THREAD

**Issue by pburnsdata** [RhoInc/crf-heat-map#97]
Currently, hovering over certain confusing column headers provides explanatory text. However, adding an info bubble by the names will make sure they know that info is available - since there's no way currently to know that hover text will appear.

# Test Notes
- Verify that info bubbles appear next to each column header
- Verify that hovering over each bubble causes explanatory text to appear. (The current text is incorrect and will be updated before release)

**Comment by dschwentker** [comment]
Tested and confirmed that info bubbles are now appearing for each column with hover text, though the actual text is still TBD.
